module.exports = {
  apps: [
    // ==============================================
    // API GATEWAY - Punto de entrada principal
    // ==============================================
    {
      name: 'api-gateway-dev',
      script: 'nest',
      args: 'start api-gateway --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false, // NestJS ya maneja el watch
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        API_GATEWAY_PORT: 3000,
        // URLs de microservicios
        AUTH_SERVICE_URL: 'http://localhost:3002',
        USERS_SERVICE_URL: 'http://localhost:3001',
        TRAINERS_SERVICE_URL: 'http://localhost:3006',
        GYMS_SERVICE_URL: 'http://localhost:3003',
        BOOKINGS_SERVICE_URL: 'http://localhost:3004',
        PAYMENTS_SERVICE_URL: 'http://localhost:3005',
      },
      error_file: './logs/api-gateway-dev-error.log',
      out_file: './logs/api-gateway-dev-out.log',
      log_file: './logs/api-gateway-dev.log',
      time: true,
    },
    // ==============================================
    // DESARROLLO - Todos los Microservicios
    // ==============================================
    {
      name: 'users-dev',
      script: 'nest',
      args: 'start users --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false, // NestJS ya maneja el watch
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT_USERS: 3001,
      },
      error_file: './logs/users-dev-error.log',
      out_file: './logs/users-dev-out.log',
      log_file: './logs/users-dev.log',
      time: true,
    },
    {
      name: 'auth-dev',
      script: 'nest',
      args: 'start auth --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT_AUTH: 3002,
      },
      error_file: './logs/auth-dev-error.log',
      out_file: './logs/auth-dev-out.log',
      log_file: './logs/auth-dev.log',
      time: true,
    },
    {
      name: 'gyms-dev',
      script: 'nest',
      args: 'start gyms --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT_GYMS: 3003,
      },
      error_file: './logs/gyms-dev-error.log',
      out_file: './logs/gyms-dev-out.log',
      log_file: './logs/gyms-dev.log',
      time: true,
    },
    {
      name: 'bookings-dev',
      script: 'nest',
      args: 'start bookings --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT_BOOKINGS: 3004,
      },
      error_file: './logs/bookings-dev-error.log',
      out_file: './logs/bookings-dev-out.log',
      log_file: './logs/bookings-dev.log',
      time: true,
    },
    {
      name: 'payments-dev',
      script: 'nest',
      args: 'start payments --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT_PAYMENTS: 3005,
      },
      error_file: './logs/payments-dev-error.log',
      out_file: './logs/payments-dev-out.log',
      log_file: './logs/payments-dev.log',
      time: true,
    },
    {
      name: 'trainers-dev',
      script: 'nest',
      args: 'start trainers --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT_TRAINERS: 3006,
      },
      error_file: './logs/trainers-dev-error.log',
      out_file: './logs/trainers-dev-out.log',
      log_file: './logs/trainers-dev.log',
      time: true,
    },
    {
      name: 'trainer-offert-dev',
      script: 'nest',
      args: 'start trainer-offert --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT_TRAINER_OFFERT: 3007,
      },
      error_file: './logs/trainer-offert-dev-error.log',
      out_file: './logs/trainer-offert-dev-out.log',
      log_file: './logs/trainer-offert-dev.log',
      time: true,
    },
    {
      name: 'routines-dev',
      script: 'nest',
      args: 'start routines --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT_ROUTINES: 3008,
      },
      error_file: './logs/routines-dev-error.log',
      out_file: './logs/routines-dev-out.log',
      log_file: './logs/routines-dev.log',
      time: true,
    },

    {
      name: 'notifications-dev',
      script: 'nest',
      args: 'start notifications --watch',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT_NOTIFICATIONS: 3009,
      },
      error_file: './logs/notifications-dev-error.log',
      out_file: './logs/notifications-dev-out.log',
      log_file: './logs/notifications-dev.log',
      time: true,
    },
  ],
}; 